version: '3.8'

services:
  api:
    environment:
      - NODE_ENV=production
    volumes: []  # Remove development volumes
    restart: unless-stopped
    command: uvicorn src.main:app --host 0.0.0.0 --port 8000

  worker:
    volumes: []  # Remove development volumes
    restart: unless-stopped

  web:
    environment:
      - NODE_ENV=production
    volumes: []  # Remove development volumes
    restart: unless-stopped
    command: npm run build && npm run serve

  db:
    restart: unless-stopped

  redis:
    restart: unless-stopped